### ISSUE TITLE
How do I use texture packs

### ISSUE THREAD

**Issue by 1qrobo1** [TheMiningTeamYT/TI84CE-Blocks-3D#6]
It says no texture packs found

**Comment by TheMiningTeamYT** [comment]
The texture packs come in the form of app vars. The default texture pack can be found with the latest release, by the name of `Default.8xv`, but other texture packs can be found in [the processing folder.](https://github.com/TheMiningTeamYT/TICraft/tree/main/processing) You download the app vars for the texture packs you want, then load them on to your calculator.
Let me know if you need any more help, otherwise go ahead and close the issue.

**Comment by TheMiningTeamYT** [comment]
Alright, with the latest release of TICraft, all the currently available texture packs are now available alongside the binary (`TICRAFT.8xp`), that is, unless you've made any yourself. Anyway, hopefully it's now easier to find the texture packs you want/need so you can get past that screen and get playing!
